-- DROP SCHEMA acme;

CREATE SCHEMA acme AUTHORIZATION postgres;

-- DROP SEQUENCE acme.audit_log_audit_log_id_seq;

CREATE SEQUENCE acme.audit_log_audit_log_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE acme.final_mail_inet_2025_final_result_id_seq;

CREATE SEQUENCE acme.final_mail_inet_2025_final_result_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE acme.final_mail_inet_2026_final_result_id_seq;

CREATE SEQUENCE acme.final_mail_inet_2026_final_result_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE acme.input_file_inventory_inventory_id_seq;

CREATE SEQUENCE acme.input_file_inventory_inventory_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- acme.audit_log definition

-- Drop table

-- DROP TABLE acme.audit_log;

CREATE TABLE acme.audit_log (
	audit_log_id bigserial NOT NULL,
	cmid varchar(9) NOT NULL,
	pnum varchar(9) NULL,
	response_table varchar(20) NULL,
	action_code varchar(10) NULL,
	var_name varchar(10) NULL,
	original_value text NULL,
	modified_value text NULL,
	process_step varchar(20) NULL,
	created_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_by text DEFAULT SESSION_USER NOT NULL,
	modified_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	modified_by text DEFAULT SESSION_USER NOT NULL,
	CONSTRAINT audit_log_pkey PRIMARY KEY (audit_log_id)
);


-- acme.final_mail_inet_2025 definition

-- Drop table

-- DROP TABLE acme.final_mail_inet_2025;

CREATE TABLE acme.final_mail_inet_2025 (
	final_result_id bigserial NOT NULL,
	survey_id varchar(2) NULL,
	survey_year varchar(4) NULL,
	response_type varchar(2) NULL,
	created_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_by text DEFAULT SESSION_USER NOT NULL,
	modified_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	modified_by text DEFAULT SESSION_USER NOT NULL,
	CONSTRAINT final_mail_inet_2025_pkey PRIMARY KEY (final_result_id)
);


-- acme.final_mail_inet_2026 definition

-- Drop table

-- DROP TABLE acme.final_mail_inet_2026;

CREATE TABLE acme.final_mail_inet_2026 (
	final_result_id bigserial NOT NULL,
	survey_id varchar(2) NULL,
	survey_year varchar(4) NULL,
	response_type varchar(2) NULL,
	created_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_by text DEFAULT SESSION_USER NOT NULL,
	modified_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	modified_by text DEFAULT SESSION_USER NOT NULL,
	CONSTRAINT final_mail_inet_2026_pkey PRIMARY KEY (final_result_id)
);


-- acme.gq_inet_population definition

-- Drop table

-- DROP TABLE acme.gq_inet_population;

CREATE TABLE acme.gq_inet_population (
	age varchar(3) NULL,
	ancw varchar(40) NULL,
	cit varchar(1) NULL,
	citw varchar(4) NULL,
	cow varchar(1) NULL,
	dbd varchar(2) NULL,
	dbm varchar(2) NULL,
	dby varchar(4) NULL,
	ddrs varchar(1) NULL,
	dear varchar(1) NULL,
	deye varchar(1) NULL,
	dout varchar(1) NULL,
	dphy varchar(1) NULL,
	drat varchar(1) NULL,
	dratx varchar(1) NULL,
	drem varchar(1) NULL,
	eng varchar(1) NULL,
	fer varchar(1) NULL,
	fname varchar(13) NULL,
	fodw varchar(255) NULL,
	fsp varchar(1) NULL,
	gcl varchar(1) NULL,
	gcm varchar(1) NULL,
	gcr varchar(1) NULL,
	hi_drect varchar(1) NULL,
	hi_emp varchar(1) NULL,
	hi_ihs varchar(1) NULL,
	hi_mcaid varchar(1) NULL,
	hi_mcare varchar(1) NULL,
	hi_none varchar(1) NULL,
	hi_oth varchar(1) NULL,
	hi_othw varchar(30) NULL,
	hi_tri varchar(1) NULL,
	hi_vet varchar(1) NULL,
	hiprem varchar(1) NULL,
	his varchar(1) NULL,
	hisub varchar(1) NULL,
	hisw varchar(200) NULL,
	inmil varchar(1) NULL,
	"int" varchar(9) NULL,
	intcalc varchar(10) NULL,
	intl varchar(1) NULL,
	intx varchar(1) NULL,
	inw2 varchar(60) NULL,
	inw3 varchar(60) NULL,
	inx4 varchar(1) NULL,
	jwam varchar(1) NULL,
	jwlh varchar(2) NULL,
	jwlm varchar(2) NULL,
	jwmn varchar(3) NULL,
	jwri varchar(2) NULL,
	jwtrns varchar(2) NULL,
	lanw varchar(30) NULL,
	lanx varchar(1) NULL,
	lname varchar(20) NULL,
	mar varchar(1) NULL,
	marhd varchar(1) NULL,
	marhm varchar(1) NULL,
	marht varchar(1) NULL,
	marhw varchar(1) NULL,
	marhy varchar(4) NULL,
	mgw1 varchar(30) NULL,
	mgw2 varchar(53) NULL,
	mgw3 varchar(20) NULL,
	mgw4 varchar(20) NULL,
	mgw5 varchar(20) NULL,
	mgw6 varchar(5) NULL,
	mi varchar(1) NULL,
	mig varchar(1) NULL,
	migx varchar(1) NULL,
	milp varchar(2) NULL,
	milsvc varchar(1) NULL,
	nwab varchar(1) NULL,
	nwav varchar(1) NULL,
	nwla varchar(1) NULL,
	nwlk varchar(1) NULL,
	nwre varchar(1) NULL,
	ocw1 varchar(60) NULL,
	ocw2 varchar(100) NULL,
	oi varchar(7) NULL,
	oix varchar(1) NULL,
	pa varchar(6) NULL,
	pax varchar(1) NULL,
	pbw2 varchar(20) NULL,
	pbw3 varchar(30) NULL,
	pbx1 varchar(1) NULL,
	pension varchar(6) NULL,
	pensionx varchar(1) NULL,
	pww1 varchar(53) NULL,
	pww2 varchar(20) NULL,
	pww4 varchar(20) NULL,
	pww5 varchar(20) NULL,
	pww6 varchar(5) NULL,
	pwx3 varchar(1) NULL,
	rac_aian varchar(1) NULL,
	rac_asnindn varchar(1) NULL,
	rac_asnoth varchar(1) NULL,
	rac_blk varchar(1) NULL,
	rac_cham varchar(1) NULL,
	rac_chn varchar(1) NULL,
	rac_fil varchar(1) NULL,
	rac_jpn varchar(1) NULL,
	rac_kor varchar(1) NULL,
	rac_nh varchar(1) NULL,
	rac_nhpioth varchar(1) NULL,
	rac_sam varchar(1) NULL,
	rac_sor varchar(1) NULL,
	rac_viet varchar(1) NULL,
	rac_wht varchar(1) NULL,
	rac_wi_aian varchar(200) NULL,
	rac_wi_asn varchar(200) NULL,
	rac_wi_blk varchar(200) NULL,
	rac_wi_nhpi varchar(200) NULL,
	rac_wi_sor varchar(200) NULL,
	rac_wi_wht varchar(200) NULL,
	rcemail varchar(50) NULL,
	remail varchar(50) NULL,
	sch varchar(1) NULL,
	schg varchar(1) NULL,
	schgw varchar(2) NULL,
	schla varchar(2) NULL,
	schlaw varchar(2) NULL,
	sem varchar(9) NULL,
	seml varchar(1) NULL,
	semx varchar(1) NULL,
	sex varchar(1) NULL,
	spartial varchar(1) NULL,
	ss varchar(6) NULL,
	ssi varchar(6) NULL,
	ssix varchar(1) NULL,
	ssx varchar(1) NULL,
	survdis varchar(6) NULL,
	survdisx varchar(1) NULL,
	ti varchar(10) NULL,
	ticalc varchar(1) NULL,
	tiest varchar(10) NULL,
	tiestl varchar(1) NULL,
	til varchar(1) NULL,
	tin varchar(1) NULL,
	wag varchar(9) NULL,
	wagx varchar(1) NULL,
	wkh varchar(3) NULL,
	wkl varchar(1) NULL,
	wkwn varchar(3) NULL,
	wkwx varchar(1) NULL,
	wrk varchar(1) NULL,
	wrkj varchar(1) NULL,
	yoe varchar(4) NULL,
	county varchar(2) NULL,
	pnum varchar(9) NOT NULL,
	CONSTRAINT pk_gq_inet_population PRIMARY KEY (pnum)
);


-- acme.gq_mail_housing definition

-- Drop table

-- DROP TABLE acme.gq_mail_housing;

CREATE TABLE acme.gq_mail_housing (
	addc1 varchar(44) NULL,
	addc2 varchar(44) NULL,
	addc3 varchar(44) NULL,
	panel varchar(6) NULL,
	qlang varchar(1) NULL,
	roomno varchar(4) NULL,
	survcode varchar(3) NULL,
	cmid varchar(9) NOT NULL,
	CONSTRAINT pk_gq_mail_housing PRIMARY KEY (cmid)
);


-- acme.hu_inet_housing definition

-- Drop table

-- DROP TABLE acme.hu_inet_housing;

CREATE TABLE acme.hu_inet_housing (
	abus varchar(1) NULL,
	"access" varchar(1) NULL,
	acr varchar(1) NULL,
	ags varchar(1) NULL,
	bath varchar(1) NULL,
	bds varchar(2) NULL,
	bld varchar(2) NULL,
	broadbnd varchar(1) NULL,
	cadd varchar(1) NULL,
	compoth varchar(1) NULL,
	compothw varchar(60) NULL,
	confee varchar(5) NULL,
	conpay varchar(1) NULL,
	conx varchar(1) NULL,
	dialup varchar(1) NULL,
	ecar varchar(1) NULL,
	ele varchar(5) NULL,
	elepay varchar(1) NULL,
	elex varchar(1) NULL,
	"fs" varchar(1) NULL,
	ful varchar(5) NULL,
	fuloth varchar(1) NULL,
	fulpay varchar(1) NULL,
	fulx varchar(1) NULL,
	gas varchar(5) NULL,
	gaspay varchar(1) NULL,
	gasuse varchar(1) NULL,
	gasx varchar(1) NULL,
	hfl varchar(1) NULL,
	hispeed varchar(1) NULL,
	idref varchar(2) NULL,
	inet_vacs varchar(1) NULL,
	ins varchar(5) NULL,
	insn varchar(1) NULL,
	intspan varchar(1) NULL,
	laptop varchar(1) NULL,
	lastda varchar(2) NULL,
	lastmo varchar(2) NULL,
	lastyr varchar(2) NULL,
	live varchar(1) NULL,
	mh varchar(6) NULL,
	mrg varchar(6) NULL,
	mrgi varchar(1) NULL,
	mrgt varchar(1) NULL,
	mrgx varchar(1) NULL,
	mvm varchar(2) NULL,
	mvy varchar(4) NULL,
	othsvce varchar(1) NULL,
	othsvcew varchar(60) NULL,
	refr varchar(1) NULL,
	rfnbus varchar(13) NULL,
	rfnresp varchar(13) NULL,
	rlive varchar(1) NULL,
	rlnbus varchar(20) NULL,
	rlnresp varchar(20) NULL,
	rmibus varchar(1) NULL,
	rmiresp varchar(1) NULL,
	rms varchar(2) NULL,
	rnt varchar(6) NULL,
	rntm varchar(1) NULL,
	rtelbus varchar(10) NULL,
	rtelresp varchar(10) NULL,
	rwat varchar(1) NULL,
	satellite varchar(1) NULL,
	sewer varchar(1) NULL,
	sink varchar(1) NULL,
	sm varchar(6) NULL,
	smartphone varchar(1) NULL,
	smx varchar(1) NULL,
	solar varchar(1) NULL,
	spartial varchar(1) NULL,
	stov varchar(1) NULL,
	tablet varchar(1) NULL,
	tax varchar(6) NULL,
	taxn varchar(1) NULL,
	tel varchar(1) NULL,
	ten varchar(1) NULL,
	val varchar(9) NULL,
	veh varchar(1) NULL,
	wat varchar(5) NULL,
	watpay varchar(1) NULL,
	watx varchar(1) NULL,
	yrblt varchar(2) NULL,
	yrbltw varchar(4) NULL,
	cmid varchar(9) NOT NULL,
	CONSTRAINT pk_hu_inet_housing PRIMARY KEY (cmid)
);


-- acme.hu_mail_housing definition

-- Drop table

-- DROP TABLE acme.hu_mail_housing;

CREATE TABLE acme.hu_mail_housing (
	"access" varchar(1) NULL,
	acr varchar(1) NULL,
	addc1 varchar(44) NULL,
	addc2 varchar(44) NULL,
	addc3 varchar(44) NULL,
	ags varchar(1) NULL,
	bath varchar(1) NULL,
	bds varchar(2) NULL,
	bld varchar(2) NULL,
	broadbnd varchar(1) NULL,
	cjic1 varchar(1) NULL,
	cjic2 varchar(1) NULL,
	cjic3 varchar(1) NULL,
	cjic4 varchar(1) NULL,
	compoth varchar(1) NULL,
	compothw varchar(60) NULL,
	con varchar(4) NULL,
	conn varchar(1) NULL,
	conx varchar(1) NULL,
	cpop varchar(3) NULL,
	dialup varchar(1) NULL,
	ecar varchar(1) NULL,
	ele varchar(4) NULL,
	elex varchar(1) NULL,
	"fs" varchar(1) NULL,
	ful varchar(4) NULL,
	fulx varchar(1) NULL,
	gas varchar(4) NULL,
	gasx varchar(1) NULL,
	hfl varchar(1) NULL,
	hispeed varchar(1) NULL,
	hotwat varchar(1) NULL,
	idy varchar(2) NULL,
	imn varchar(2) NULL,
	ins varchar(4) NULL,
	insn varchar(1) NULL,
	iyr varchar(4) NULL,
	laptop varchar(1) NULL,
	mh varchar(5) NULL,
	mrg varchar(5) NULL,
	mrgi varchar(1) NULL,
	mrgn varchar(1) NULL,
	mrgt varchar(1) NULL,
	mrgx varchar(1) NULL,
	mvm varchar(2) NULL,
	mvy varchar(4) NULL,
	othsvce varchar(1) NULL,
	othsvcew varchar(60) NULL,
	panel varchar(6) NULL,
	prflag varchar(1) NULL,
	prvin varchar(8) NULL,
	prvout varchar(4) NULL,
	refr varchar(1) NULL,
	resp varchar(2) NULL,
	rfn varchar(13) NULL,
	rln varchar(20) NULL,
	rmi varchar(1) NULL,
	rms varchar(2) NULL,
	rnt varchar(5) NULL,
	rntm varchar(1) NULL,
	rper varchar(2) NULL,
	rtel varchar(10) NULL,
	rwat varchar(1) NULL,
	rwatpr varchar(1) NULL,
	satellite varchar(1) NULL,
	sewer varchar(1) NULL,
	sink varchar(1) NULL,
	sm varchar(5) NULL,
	smartphone varchar(1) NULL,
	smn varchar(1) NULL,
	smx varchar(1) NULL,
	solar varchar(1) NULL,
	stov varchar(1) NULL,
	survcode varchar(3) NULL,
	tablet varchar(1) NULL,
	tax varchar(5) NULL,
	taxn varchar(1) NULL,
	tel varchar(1) NULL,
	ten varchar(1) NULL,
	val varchar(7) NULL,
	veh varchar(1) NULL,
	wat varchar(4) NULL,
	watx varchar(1) NULL,
	yrblt varchar(2) NULL,
	yrbltw varchar(4) NULL,
	cmid varchar(9) NOT NULL,
	CONSTRAINT pk_hu_mail_housing PRIMARY KEY (cmid)
);


-- acme.input_file_inventory definition

-- Drop table

-- DROP TABLE acme.input_file_inventory;

CREATE TABLE acme.input_file_inventory (
	inventory_id bigserial NOT NULL,
	s3_bucket varchar NULL,
	file_name_s3_key varchar NULL,
	created_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_by text DEFAULT SESSION_USER NOT NULL,
	modified_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	modified_by text DEFAULT SESSION_USER NOT NULL,
	CONSTRAINT input_file_inventory_pkey PRIMARY KEY (inventory_id)
);


-- acme.gq_mail_group_quarters definition

-- Drop table

-- DROP TABLE acme.gq_mail_group_quarters;

CREATE TABLE acme.gq_mail_group_quarters (
	fdy varchar(3) NULL,
	fmn varchar(3) NULL,
	frbondid varchar(8) NULL,
	frcode varchar(3) NULL,
	frn varchar(30) NULL,
	fsp varchar(1) NULL,
	fyr varchar(4) NULL,
	"out" varchar(2) NULL,
	outw varchar(3) NULL,
	qadmin varchar(1) NULL,
	qcomp varchar(1) NULL,
	qcompw varchar(30) NULL,
	reason varchar(30) NULL,
	whoans varchar(1) NULL,
	cmid varchar(9) NOT NULL,
	CONSTRAINT pk_gq_mail_group_quarters PRIMARY KEY (cmid),
	CONSTRAINT fk_gq_mail_group_quarters_gq_mail_housing FOREIGN KEY (cmid) REFERENCES acme.gq_mail_housing(cmid)
);


-- acme.gq_mail_population definition

-- Drop table

-- DROP TABLE acme.gq_mail_population;

CREATE TABLE acme.gq_mail_population (
	age varchar(3) NULL,
	ancw varchar(40) NULL,
	cit varchar(1) NULL,
	citw varchar(4) NULL,
	cow varchar(1) NULL,
	dbd varchar(2) NULL,
	dbm varchar(2) NULL,
	dby varchar(4) NULL,
	ddrs varchar(1) NULL,
	dear varchar(1) NULL,
	deye varchar(1) NULL,
	dout varchar(1) NULL,
	dphy varchar(1) NULL,
	drat varchar(1) NULL,
	dratx varchar(1) NULL,
	drem varchar(1) NULL,
	eng varchar(1) NULL,
	fer varchar(1) NULL,
	fn varchar(13) NULL,
	fodw varchar(255) NULL,
	gcl varchar(1) NULL,
	gcm varchar(1) NULL,
	gcr varchar(1) NULL,
	hi_drect varchar(1) NULL,
	hi_emp varchar(1) NULL,
	hi_ihs varchar(1) NULL,
	hi_mcaid varchar(1) NULL,
	hi_mcare varchar(1) NULL,
	hi_none varchar(1) NULL,
	hi_oth varchar(1) NULL,
	hi_othw varchar(30) NULL,
	hi_tri varchar(1) NULL,
	hi_vet varchar(1) NULL,
	hiprem varchar(1) NULL,
	his varchar(1) NULL,
	hisub varchar(1) NULL,
	hisw varchar(200) NULL,
	idy varchar(2) NULL,
	imn varchar(2) NULL,
	"int" varchar(7) NULL,
	intl varchar(1) NULL,
	intx varchar(1) NULL,
	inw2 varchar(60) NULL,
	inw3 varchar(60) NULL,
	inx4 varchar(1) NULL,
	iyr varchar(4) NULL,
	jwam varchar(1) NULL,
	jwlh varchar(2) NULL,
	jwlm varchar(2) NULL,
	jwmn varchar(3) NULL,
	jwri varchar(2) NULL,
	jwtrns varchar(2) NULL,
	lanw varchar(30) NULL,
	lanx varchar(1) NULL,
	"ln" varchar(20) NULL,
	mar varchar(1) NULL,
	marhd varchar(1) NULL,
	marhm varchar(1) NULL,
	marht varchar(1) NULL,
	marhw varchar(1) NULL,
	marhy varchar(4) NULL,
	mgw1 varchar(30) NULL,
	mgw2 varchar(53) NULL,
	mgw3 varchar(20) NULL,
	mgw4 varchar(20) NULL,
	mgw5 varchar(20) NULL,
	mgw6 varchar(5) NULL,
	mi varchar(1) NULL,
	mig varchar(1) NULL,
	milp varchar(2) NULL,
	milsvc varchar(1) NULL,
	nwab varchar(1) NULL,
	nwav varchar(1) NULL,
	nwla varchar(1) NULL,
	nwlk varchar(1) NULL,
	nwre varchar(1) NULL,
	ocw1 varchar(60) NULL,
	ocw2 varchar(100) NULL,
	oi varchar(6) NULL,
	oix varchar(1) NULL,
	pa varchar(5) NULL,
	pax varchar(1) NULL,
	pbw2 varchar(20) NULL,
	pbw3 varchar(30) NULL,
	pbx1 varchar(1) NULL,
	pww1 varchar(53) NULL,
	pww2 varchar(20) NULL,
	pww4 varchar(20) NULL,
	pww5 varchar(20) NULL,
	pww6 varchar(5) NULL,
	pwx3 varchar(1) NULL,
	rac_aian varchar(1) NULL,
	rac_asnindn varchar(1) NULL,
	rac_asnoth varchar(1) NULL,
	rac_blk varchar(1) NULL,
	rac_cham varchar(1) NULL,
	rac_chn varchar(1) NULL,
	rac_fil varchar(1) NULL,
	rac_jpn varchar(1) NULL,
	rac_kor varchar(1) NULL,
	rac_nh varchar(1) NULL,
	rac_nhpioth varchar(1) NULL,
	rac_sam varchar(1) NULL,
	rac_sor varchar(1) NULL,
	rac_viet varchar(1) NULL,
	rac_wht varchar(1) NULL,
	rac_wi_aian varchar(200) NULL,
	rac_wi_asn varchar(200) NULL,
	rac_wi_blk varchar(200) NULL,
	rac_wi_nhpi varchar(200) NULL,
	rac_wi_sor varchar(200) NULL,
	rac_wi_wht varchar(200) NULL,
	ret varchar(6) NULL,
	retx varchar(1) NULL,
	rtel varchar(10) NULL,
	sch varchar(1) NULL,
	schg varchar(1) NULL,
	schgw varchar(2) NULL,
	schla varchar(2) NULL,
	schlaw varchar(2) NULL,
	sem varchar(7) NULL,
	seml varchar(1) NULL,
	semx varchar(1) NULL,
	sex varchar(1) NULL,
	ss varchar(5) NULL,
	ssi varchar(5) NULL,
	ssix varchar(1) NULL,
	ssx varchar(1) NULL,
	ti varchar(8) NULL,
	til varchar(1) NULL,
	tin varchar(1) NULL,
	wag varchar(7) NULL,
	wagx varchar(1) NULL,
	wkh varchar(3) NULL,
	wkl varchar(1) NULL,
	wkwn varchar(2) NULL,
	wkwx varchar(1) NULL,
	wrk varchar(1) NULL,
	wrkj varchar(1) NULL,
	yoe varchar(4) NULL,
	cmid varchar(9) NOT NULL,
	pnum varchar(9) NOT NULL,
	CONSTRAINT pk_gq_mail_population PRIMARY KEY (cmid, pnum),
	CONSTRAINT fk_gq_mail_population_gq_mail_housing FOREIGN KEY (cmid) REFERENCES acme.gq_mail_housing(cmid)
);


-- acme.hu_inet_population definition

-- Drop table

-- DROP TABLE acme.hu_inet_population;

CREATE TABLE acme.hu_inet_population (
	age varchar(3) NULL,
	ancw varchar(40) NULL,
	cit varchar(1) NULL,
	citw varchar(4) NULL,
	cow varchar(1) NULL,
	dbd varchar(2) NULL,
	dbm varchar(2) NULL,
	dby varchar(4) NULL,
	ddrs varchar(1) NULL,
	dear varchar(1) NULL,
	deye varchar(1) NULL,
	dout varchar(1) NULL,
	dphy varchar(1) NULL,
	drat varchar(1) NULL,
	dratx varchar(1) NULL,
	drem varchar(1) NULL,
	eng varchar(1) NULL,
	fer varchar(1) NULL,
	fname varchar(13) NULL,
	fodw varchar(255) NULL,
	gcl varchar(1) NULL,
	gcm varchar(1) NULL,
	gcr varchar(1) NULL,
	hi_drect varchar(1) NULL,
	hi_emp varchar(1) NULL,
	hi_ihs varchar(1) NULL,
	hi_mcaid varchar(1) NULL,
	hi_mcare varchar(1) NULL,
	hi_none varchar(1) NULL,
	hi_oth varchar(1) NULL,
	hi_othw varchar(30) NULL,
	hi_tri varchar(1) NULL,
	hi_vet varchar(1) NULL,
	hiprem varchar(1) NULL,
	his varchar(1) NULL,
	hisub varchar(1) NULL,
	hisw varchar(200) NULL,
	inmil varchar(1) NULL,
	"int" varchar(9) NULL,
	intcalc varchar(10) NULL,
	intl varchar(1) NULL,
	intx varchar(1) NULL,
	inw2 varchar(60) NULL,
	inw3 varchar(60) NULL,
	inx4 varchar(1) NULL,
	jwam varchar(1) NULL,
	jwlh varchar(2) NULL,
	jwlm varchar(2) NULL,
	jwmn varchar(3) NULL,
	jwri varchar(2) NULL,
	jwtrns varchar(2) NULL,
	lanw varchar(30) NULL,
	lanx varchar(1) NULL,
	lname varchar(20) NULL,
	mar varchar(1) NULL,
	marhd varchar(1) NULL,
	marhm varchar(1) NULL,
	marht varchar(1) NULL,
	marhw varchar(1) NULL,
	marhy varchar(4) NULL,
	mgw1 varchar(30) NULL,
	mgw2 varchar(53) NULL,
	mgw3 varchar(20) NULL,
	mgw4 varchar(20) NULL,
	mgw5 varchar(20) NULL,
	mgw6 varchar(5) NULL,
	mi varchar(1) NULL,
	mig varchar(1) NULL,
	migpnum varchar(1) NULL,
	migx varchar(1) NULL,
	milp varchar(2) NULL,
	milsvc varchar(1) NULL,
	nwab varchar(1) NULL,
	nwav varchar(1) NULL,
	nwla varchar(1) NULL,
	nwlk varchar(1) NULL,
	nwre varchar(1) NULL,
	ocw1 varchar(60) NULL,
	ocw2 varchar(100) NULL,
	oi varchar(7) NULL,
	oix varchar(1) NULL,
	pa varchar(6) NULL,
	pax varchar(1) NULL,
	pbw2 varchar(20) NULL,
	pbw3 varchar(30) NULL,
	pbx1 varchar(1) NULL,
	pension varchar(6) NULL,
	pensionx varchar(1) NULL,
	pww1 varchar(53) NULL,
	pww2 varchar(20) NULL,
	pww4 varchar(20) NULL,
	pww5 varchar(20) NULL,
	pww6 varchar(5) NULL,
	pwx3 varchar(1) NULL,
	rac_aian varchar(1) NULL,
	rac_asnindn varchar(1) NULL,
	rac_asnoth varchar(1) NULL,
	rac_blk varchar(1) NULL,
	rac_cham varchar(1) NULL,
	rac_chn varchar(1) NULL,
	rac_fil varchar(1) NULL,
	rac_jpn varchar(1) NULL,
	rac_kor varchar(1) NULL,
	rac_nh varchar(1) NULL,
	rac_nhpioth varchar(1) NULL,
	rac_sam varchar(1) NULL,
	rac_sor varchar(1) NULL,
	rac_viet varchar(1) NULL,
	rac_wht varchar(1) NULL,
	rac_wi_aian varchar(200) NULL,
	rac_wi_asn varchar(200) NULL,
	rac_wi_blk varchar(200) NULL,
	rac_wi_nhpi varchar(200) NULL,
	rac_wi_sor varchar(200) NULL,
	rac_wi_wht varchar(200) NULL,
	refper varchar(1) NULL,
	relship varchar(2) NULL,
	sch varchar(1) NULL,
	schg varchar(1) NULL,
	schgw varchar(2) NULL,
	schla varchar(2) NULL,
	schlaw varchar(2) NULL,
	sem varchar(9) NULL,
	seml varchar(1) NULL,
	semx varchar(1) NULL,
	sex varchar(1) NULL,
	ss varchar(6) NULL,
	ssi varchar(6) NULL,
	ssix varchar(1) NULL,
	ssx varchar(1) NULL,
	survdis varchar(6) NULL,
	survdisx varchar(1) NULL,
	ti varchar(10) NULL,
	ticalc varchar(1) NULL,
	tiest varchar(10) NULL,
	tiestl varchar(1) NULL,
	til varchar(1) NULL,
	tin varchar(1) NULL,
	wag varchar(9) NULL,
	wagx varchar(1) NULL,
	wkh varchar(3) NULL,
	wkl varchar(1) NULL,
	wkwn varchar(3) NULL,
	wkwx varchar(1) NULL,
	wrk varchar(1) NULL,
	wrkj varchar(1) NULL,
	yoe varchar(4) NULL,
	cmid varchar(9) NOT NULL,
	pnum varchar(9) NOT NULL,
	CONSTRAINT pk_hu_inet_population PRIMARY KEY (cmid, pnum),
	CONSTRAINT fk_hu_inet_population_hu_inet_housing FOREIGN KEY (cmid) REFERENCES acme.hu_inet_housing(cmid)
);


-- acme.hu_inet_roster definition

-- Drop table

-- DROP TABLE acme.hu_inet_roster;

CREATE TABLE acme.hu_inet_roster (
	addrcolw1 varchar(20) NULL,
	addrcolw2 varchar(50) NULL,
	addrcolw3 varchar(50) NULL,
	addrcolw4 varchar(100) NULL,
	addrcolw5 varchar(20) NULL,
	addrcolw6 varchar(5) NULL,
	addrcolw8 varchar(250) NULL,
	addrcolx7 varchar(1) NULL,
	anoth01 varchar(34) NULL,
	anoth02 varchar(34) NULL,
	anoth03 varchar(34) NULL,
	anoth04 varchar(34) NULL,
	anoth05 varchar(34) NULL,
	anoth06 varchar(34) NULL,
	anoth07 varchar(34) NULL,
	anoth08 varchar(34) NULL,
	anoth09 varchar(34) NULL,
	anoth10 varchar(34) NULL,
	anoth11 varchar(34) NULL,
	anoth12 varchar(34) NULL,
	anoth13 varchar(34) NULL,
	anoth14 varchar(34) NULL,
	anoth15 varchar(34) NULL,
	anoth16 varchar(34) NULL,
	anoth17 varchar(34) NULL,
	anoth18 varchar(34) NULL,
	anoth19 varchar(34) NULL,
	anoth20 varchar(34) NULL,
	anoth21 varchar(34) NULL,
	anoth22 varchar(34) NULL,
	anoth23 varchar(34) NULL,
	anoth24 varchar(34) NULL,
	anoth25 varchar(34) NULL,
	anoth26 varchar(34) NULL,
	anoth27 varchar(34) NULL,
	anoth28 varchar(34) NULL,
	anoth29 varchar(34) NULL,
	anoth30 varchar(34) NULL,
	anoth31 varchar(34) NULL,
	anoth32 varchar(34) NULL,
	anoth33 varchar(34) NULL,
	anoth34 varchar(34) NULL,
	anoth35 varchar(34) NULL,
	anoth36 varchar(34) NULL,
	anoth37 varchar(34) NULL,
	anoth38 varchar(34) NULL,
	anoth39 varchar(34) NULL,
	anoth40 varchar(34) NULL,
	anoth41 varchar(34) NULL,
	anoth42 varchar(34) NULL,
	anoth43 varchar(34) NULL,
	anoth44 varchar(34) NULL,
	anoth45 varchar(34) NULL,
	anoth46 varchar(34) NULL,
	anoth47 varchar(34) NULL,
	anoth48 varchar(34) NULL,
	anoth49 varchar(34) NULL,
	anoth50 varchar(34) NULL,
	anoth51 varchar(34) NULL,
	anoth52 varchar(34) NULL,
	anoth53 varchar(34) NULL,
	anoth54 varchar(34) NULL,
	anoth55 varchar(34) NULL,
	anoth56 varchar(34) NULL,
	anoth57 varchar(34) NULL,
	anotherx varchar(1) NULL,
	away01 varchar(34) NULL,
	away02 varchar(34) NULL,
	away03 varchar(34) NULL,
	away04 varchar(34) NULL,
	away05 varchar(34) NULL,
	away06 varchar(34) NULL,
	away07 varchar(34) NULL,
	away08 varchar(34) NULL,
	away09 varchar(34) NULL,
	away10 varchar(34) NULL,
	away11 varchar(34) NULL,
	away12 varchar(34) NULL,
	away13 varchar(34) NULL,
	away14 varchar(34) NULL,
	away15 varchar(34) NULL,
	away16 varchar(34) NULL,
	away17 varchar(34) NULL,
	away18 varchar(34) NULL,
	away19 varchar(34) NULL,
	away20 varchar(34) NULL,
	away21 varchar(34) NULL,
	away22 varchar(34) NULL,
	away23 varchar(34) NULL,
	away24 varchar(34) NULL,
	away25 varchar(34) NULL,
	away26 varchar(34) NULL,
	away27 varchar(34) NULL,
	away28 varchar(34) NULL,
	away29 varchar(34) NULL,
	away30 varchar(34) NULL,
	away31 varchar(34) NULL,
	away32 varchar(34) NULL,
	away33 varchar(34) NULL,
	away34 varchar(34) NULL,
	away35 varchar(34) NULL,
	away36 varchar(34) NULL,
	away37 varchar(34) NULL,
	away38 varchar(34) NULL,
	away39 varchar(34) NULL,
	away40 varchar(34) NULL,
	away41 varchar(34) NULL,
	away42 varchar(34) NULL,
	away43 varchar(34) NULL,
	away44 varchar(34) NULL,
	away45 varchar(34) NULL,
	away46 varchar(34) NULL,
	away47 varchar(34) NULL,
	away48 varchar(34) NULL,
	away49 varchar(34) NULL,
	away50 varchar(34) NULL,
	away51 varchar(34) NULL,
	away52 varchar(34) NULL,
	away53 varchar(34) NULL,
	away54 varchar(34) NULL,
	away55 varchar(34) NULL,
	away56 varchar(34) NULL,
	away57 varchar(34) NULL,
	awayx varchar(1) NULL,
	mortwo01 varchar(1) NULL,
	mortwo02 varchar(1) NULL,
	mortwo03 varchar(1) NULL,
	mortwo04 varchar(1) NULL,
	mortwo05 varchar(1) NULL,
	mortwo06 varchar(1) NULL,
	mortwo07 varchar(1) NULL,
	mortwo08 varchar(1) NULL,
	mortwo09 varchar(1) NULL,
	mortwo10 varchar(1) NULL,
	mortwo11 varchar(1) NULL,
	mortwo12 varchar(1) NULL,
	mortwo13 varchar(1) NULL,
	mortwo14 varchar(1) NULL,
	mortwo15 varchar(1) NULL,
	mortwo16 varchar(1) NULL,
	mortwo17 varchar(1) NULL,
	mortwo18 varchar(1) NULL,
	mortwo19 varchar(1) NULL,
	mortwo20 varchar(1) NULL,
	mortwo21 varchar(1) NULL,
	mortwo22 varchar(1) NULL,
	mortwo23 varchar(1) NULL,
	mortwo24 varchar(1) NULL,
	mortwo25 varchar(1) NULL,
	mortwo26 varchar(1) NULL,
	mortwo27 varchar(1) NULL,
	mortwo28 varchar(1) NULL,
	mortwo29 varchar(1) NULL,
	mortwo30 varchar(1) NULL,
	mortwo31 varchar(1) NULL,
	mortwo32 varchar(1) NULL,
	mortwo33 varchar(1) NULL,
	mortwo34 varchar(1) NULL,
	mortwo35 varchar(1) NULL,
	mortwo36 varchar(1) NULL,
	mortwo37 varchar(1) NULL,
	mortwo38 varchar(1) NULL,
	mortwo39 varchar(1) NULL,
	mortwo40 varchar(1) NULL,
	mortwo41 varchar(1) NULL,
	mortwo42 varchar(1) NULL,
	mortwo43 varchar(1) NULL,
	mortwo44 varchar(1) NULL,
	mortwo45 varchar(1) NULL,
	mortwo46 varchar(1) NULL,
	mortwo47 varchar(1) NULL,
	mortwo48 varchar(1) NULL,
	mortwo49 varchar(1) NULL,
	mortwo50 varchar(1) NULL,
	mortwo51 varchar(1) NULL,
	mortwo52 varchar(1) NULL,
	mortwo53 varchar(1) NULL,
	mortwo54 varchar(1) NULL,
	mortwo55 varchar(1) NULL,
	mortwo56 varchar(1) NULL,
	rcemail varchar(50) NULL,
	remail varchar(50) NULL,
	rostaf01 varchar(13) NULL,
	rostaf02 varchar(13) NULL,
	rostaf03 varchar(13) NULL,
	rostaf04 varchar(13) NULL,
	rostaf05 varchar(13) NULL,
	rostaf06 varchar(13) NULL,
	rostaf07 varchar(13) NULL,
	rostaf08 varchar(13) NULL,
	rostaf09 varchar(13) NULL,
	rostaf10 varchar(13) NULL,
	rostaf11 varchar(13) NULL,
	rostaf12 varchar(13) NULL,
	rostaf13 varchar(13) NULL,
	rostaf14 varchar(13) NULL,
	rostaf15 varchar(13) NULL,
	rostaf16 varchar(13) NULL,
	rostaf17 varchar(13) NULL,
	rostaf18 varchar(13) NULL,
	rostaf19 varchar(13) NULL,
	rostaf20 varchar(13) NULL,
	rostal01 varchar(20) NULL,
	rostal02 varchar(20) NULL,
	rostal03 varchar(20) NULL,
	rostal04 varchar(20) NULL,
	rostal05 varchar(20) NULL,
	rostal06 varchar(20) NULL,
	rostal07 varchar(20) NULL,
	rostal08 varchar(20) NULL,
	rostal09 varchar(20) NULL,
	rostal10 varchar(20) NULL,
	rostal11 varchar(20) NULL,
	rostal12 varchar(20) NULL,
	rostal13 varchar(20) NULL,
	rostal14 varchar(20) NULL,
	rostal15 varchar(20) NULL,
	rostal16 varchar(20) NULL,
	rostal17 varchar(20) NULL,
	rostal18 varchar(20) NULL,
	rostal19 varchar(20) NULL,
	rostal20 varchar(20) NULL,
	rostam01 varchar(1) NULL,
	rostam02 varchar(1) NULL,
	rostam03 varchar(1) NULL,
	rostam04 varchar(1) NULL,
	rostam05 varchar(1) NULL,
	rostam06 varchar(1) NULL,
	rostam07 varchar(1) NULL,
	rostam08 varchar(1) NULL,
	rostam09 varchar(1) NULL,
	rostam10 varchar(1) NULL,
	rostam11 varchar(1) NULL,
	rostam12 varchar(1) NULL,
	rostam13 varchar(1) NULL,
	rostam14 varchar(1) NULL,
	rostam15 varchar(1) NULL,
	rostam16 varchar(1) NULL,
	rostam17 varchar(1) NULL,
	rostam18 varchar(1) NULL,
	rostam19 varchar(1) NULL,
	rostam20 varchar(1) NULL,
	rostbf21 varchar(13) NULL,
	rostbf22 varchar(13) NULL,
	rostbf23 varchar(13) NULL,
	rostbf24 varchar(13) NULL,
	rostbf25 varchar(13) NULL,
	rostbf26 varchar(13) NULL,
	rostbf27 varchar(13) NULL,
	rostbf28 varchar(13) NULL,
	rostbf29 varchar(13) NULL,
	rostbf30 varchar(13) NULL,
	rostbf31 varchar(13) NULL,
	rostbf32 varchar(13) NULL,
	rostbf33 varchar(13) NULL,
	rostbf34 varchar(13) NULL,
	rostbf35 varchar(13) NULL,
	rostbf36 varchar(13) NULL,
	rostbf37 varchar(13) NULL,
	rostbf38 varchar(13) NULL,
	rostbl21 varchar(20) NULL,
	rostbl22 varchar(20) NULL,
	rostbl23 varchar(20) NULL,
	rostbl24 varchar(20) NULL,
	rostbl25 varchar(20) NULL,
	rostbl26 varchar(20) NULL,
	rostbl27 varchar(20) NULL,
	rostbl28 varchar(20) NULL,
	rostbl29 varchar(20) NULL,
	rostbl30 varchar(20) NULL,
	rostbl31 varchar(20) NULL,
	rostbl32 varchar(20) NULL,
	rostbl33 varchar(20) NULL,
	rostbl34 varchar(20) NULL,
	rostbl35 varchar(20) NULL,
	rostbl36 varchar(20) NULL,
	rostbl37 varchar(20) NULL,
	rostbl38 varchar(20) NULL,
	rostbm21 varchar(1) NULL,
	rostbm22 varchar(1) NULL,
	rostbm23 varchar(1) NULL,
	rostbm24 varchar(1) NULL,
	rostbm25 varchar(1) NULL,
	rostbm26 varchar(1) NULL,
	rostbm27 varchar(1) NULL,
	rostbm28 varchar(1) NULL,
	rostbm29 varchar(1) NULL,
	rostbm30 varchar(1) NULL,
	rostbm31 varchar(1) NULL,
	rostbm32 varchar(1) NULL,
	rostbm33 varchar(1) NULL,
	rostbm34 varchar(1) NULL,
	rostbm35 varchar(1) NULL,
	rostbm36 varchar(1) NULL,
	rostbm37 varchar(1) NULL,
	rostbm38 varchar(1) NULL,
	rostbx varchar(1) NULL,
	rostcf39 varchar(13) NULL,
	rostcf40 varchar(13) NULL,
	rostcf41 varchar(13) NULL,
	rostcf42 varchar(13) NULL,
	rostcf43 varchar(13) NULL,
	rostcf44 varchar(13) NULL,
	rostcf45 varchar(13) NULL,
	rostcf46 varchar(13) NULL,
	rostcf47 varchar(13) NULL,
	rostcf48 varchar(13) NULL,
	rostcf49 varchar(13) NULL,
	rostcf51 varchar(13) NULL,
	rostcf52 varchar(13) NULL,
	rostcf53 varchar(13) NULL,
	rostcf54 varchar(13) NULL,
	rostcf55 varchar(13) NULL,
	rostcf56 varchar(13) NULL,
	rostcl39 varchar(20) NULL,
	rostcl40 varchar(20) NULL,
	rostcl41 varchar(20) NULL,
	rostcl42 varchar(20) NULL,
	rostcl43 varchar(20) NULL,
	rostcl44 varchar(20) NULL,
	rostcl45 varchar(20) NULL,
	rostcl46 varchar(20) NULL,
	rostcl47 varchar(20) NULL,
	rostcl48 varchar(20) NULL,
	rostcl49 varchar(20) NULL,
	rostcl50 varchar(20) NULL,
	rostcl51 varchar(20) NULL,
	rostcl52 varchar(20) NULL,
	rostcl53 varchar(20) NULL,
	rostcl54 varchar(20) NULL,
	rostcl55 varchar(20) NULL,
	rostcl56 varchar(20) NULL,
	rostcm39 varchar(1) NULL,
	rostcm40 varchar(1) NULL,
	rostcm41 varchar(1) NULL,
	rostcm42 varchar(1) NULL,
	rostcm43 varchar(1) NULL,
	rostcm44 varchar(1) NULL,
	rostcm45 varchar(1) NULL,
	rostcm46 varchar(1) NULL,
	rostcm47 varchar(1) NULL,
	rostcm48 varchar(1) NULL,
	rostcm49 varchar(1) NULL,
	rostcm50 varchar(1) NULL,
	rostcm51 varchar(1) NULL,
	rostcm52 varchar(1) NULL,
	rostcm53 varchar(1) NULL,
	rostcm54 varchar(1) NULL,
	rostcm55 varchar(1) NULL,
	rostcm56 varchar(1) NULL,
	rostcx varchar(1) NULL,
	roststay01 varchar(1) NULL,
	roststay02 varchar(1) NULL,
	roststay03 varchar(1) NULL,
	roststay04 varchar(1) NULL,
	roststay05 varchar(1) NULL,
	roststay06 varchar(1) NULL,
	roststay07 varchar(1) NULL,
	roststay08 varchar(1) NULL,
	roststay09 varchar(1) NULL,
	roststay10 varchar(1) NULL,
	roststay11 varchar(1) NULL,
	roststay12 varchar(1) NULL,
	roststay13 varchar(1) NULL,
	roststay14 varchar(1) NULL,
	roststay15 varchar(1) NULL,
	roststay16 varchar(1) NULL,
	roststay17 varchar(1) NULL,
	roststay18 varchar(1) NULL,
	roststay19 varchar(1) NULL,
	roststay20 varchar(1) NULL,
	roststay21 varchar(1) NULL,
	roststay22 varchar(1) NULL,
	roststay23 varchar(1) NULL,
	roststay24 varchar(1) NULL,
	roststay25 varchar(1) NULL,
	roststay26 varchar(1) NULL,
	roststay27 varchar(1) NULL,
	roststay28 varchar(1) NULL,
	roststay29 varchar(1) NULL,
	roststay30 varchar(1) NULL,
	roststay31 varchar(1) NULL,
	roststay32 varchar(1) NULL,
	roststay33 varchar(1) NULL,
	roststay34 varchar(1) NULL,
	roststay35 varchar(1) NULL,
	roststay36 varchar(1) NULL,
	roststay37 varchar(1) NULL,
	roststay38 varchar(1) NULL,
	roststay39 varchar(1) NULL,
	roststay40 varchar(1) NULL,
	roststay41 varchar(1) NULL,
	roststay42 varchar(1) NULL,
	roststay43 varchar(1) NULL,
	roststay44 varchar(1) NULL,
	roststay45 varchar(1) NULL,
	roststay46 varchar(1) NULL,
	roststay47 varchar(1) NULL,
	roststay48 varchar(1) NULL,
	roststay49 varchar(1) NULL,
	roststay50 varchar(1) NULL,
	roststay51 varchar(1) NULL,
	roststay52 varchar(1) NULL,
	roststay53 varchar(1) NULL,
	roststay54 varchar(1) NULL,
	roststay55 varchar(1) NULL,
	roststay56 varchar(1) NULL,
	cmid varchar(9) NOT NULL,
	CONSTRAINT pk_hu_inet_roster PRIMARY KEY (cmid),
	CONSTRAINT fk_hu_inet_roster_hu_inet_housing FOREIGN KEY (cmid) REFERENCES acme.hu_inet_housing(cmid)
);


-- acme.hu_mail_population definition

-- Drop table

-- DROP TABLE acme.hu_mail_population;

CREATE TABLE acme.hu_mail_population (
	age varchar(3) NULL,
	ancw varchar(40) NULL,
	cit varchar(1) NULL,
	citw varchar(4) NULL,
	cow varchar(1) NULL,
	dbd varchar(2) NULL,
	dbm varchar(2) NULL,
	dby varchar(4) NULL,
	ddrs varchar(1) NULL,
	dear varchar(1) NULL,
	deye varchar(1) NULL,
	dout varchar(1) NULL,
	dphy varchar(1) NULL,
	drat varchar(1) NULL,
	dratx varchar(1) NULL,
	drem varchar(1) NULL,
	eng varchar(1) NULL,
	fer varchar(1) NULL,
	fn varchar(13) NULL,
	fn_basic varchar(13) NULL,
	fodw varchar(255) NULL,
	gcl varchar(1) NULL,
	gcm varchar(1) NULL,
	gcr varchar(1) NULL,
	hi_drect varchar(1) NULL,
	hi_emp varchar(1) NULL,
	hi_ihs varchar(1) NULL,
	hi_mcaid varchar(1) NULL,
	hi_mcare varchar(1) NULL,
	hi_none varchar(1) NULL,
	hi_oth varchar(1) NULL,
	hi_othw varchar(30) NULL,
	hi_tri varchar(1) NULL,
	hi_vet varchar(1) NULL,
	hiprem varchar(1) NULL,
	his varchar(1) NULL,
	hisub varchar(1) NULL,
	hisw varchar(200) NULL,
	"int" varchar(7) NULL,
	intl varchar(1) NULL,
	intx varchar(1) NULL,
	inw2 varchar(60) NULL,
	inw3 varchar(60) NULL,
	inx4 varchar(1) NULL,
	jwam varchar(1) NULL,
	jwlh varchar(2) NULL,
	jwlm varchar(2) NULL,
	jwmn varchar(3) NULL,
	jwri varchar(2) NULL,
	jwtrns varchar(2) NULL,
	lanw varchar(30) NULL,
	lanx varchar(1) NULL,
	"ln" varchar(20) NULL,
	ln_basic varchar(20) NULL,
	mar varchar(1) NULL,
	marhd varchar(1) NULL,
	marhm varchar(1) NULL,
	marht varchar(1) NULL,
	marhw varchar(1) NULL,
	marhy varchar(4) NULL,
	mgw1 varchar(30) NULL,
	mgw2 varchar(53) NULL,
	mgw3 varchar(20) NULL,
	mgw4 varchar(20) NULL,
	mgw5 varchar(20) NULL,
	mgw6 varchar(5) NULL,
	mi varchar(1) NULL,
	mi_basic varchar(1) NULL,
	mig varchar(1) NULL,
	milp varchar(2) NULL,
	milsvc varchar(1) NULL,
	nwab varchar(1) NULL,
	nwav varchar(1) NULL,
	nwla varchar(1) NULL,
	nwlk varchar(1) NULL,
	nwre varchar(1) NULL,
	ocw1 varchar(60) NULL,
	ocw2 varchar(100) NULL,
	oi varchar(6) NULL,
	oix varchar(1) NULL,
	pa varchar(5) NULL,
	pax varchar(1) NULL,
	pbw2 varchar(20) NULL,
	pbw3 varchar(30) NULL,
	pbx1 varchar(1) NULL,
	pww1 varchar(53) NULL,
	pww2 varchar(20) NULL,
	pww4 varchar(20) NULL,
	pww5 varchar(20) NULL,
	pww6 varchar(5) NULL,
	pwx3 varchar(1) NULL,
	rac_aian varchar(1) NULL,
	rac_asnindn varchar(1) NULL,
	rac_asnoth varchar(1) NULL,
	rac_blk varchar(1) NULL,
	rac_cham varchar(1) NULL,
	rac_chn varchar(1) NULL,
	rac_fil varchar(1) NULL,
	rac_jpn varchar(1) NULL,
	rac_kor varchar(1) NULL,
	rac_nh varchar(1) NULL,
	rac_nhpioth varchar(1) NULL,
	rac_sam varchar(1) NULL,
	rac_sor varchar(1) NULL,
	rac_viet varchar(1) NULL,
	rac_wht varchar(1) NULL,
	rac_wi_aian varchar(200) NULL,
	rac_wi_asn varchar(200) NULL,
	rac_wi_blk varchar(200) NULL,
	rac_wi_nhpi varchar(200) NULL,
	rac_wi_sor varchar(200) NULL,
	rac_wi_wht varchar(200) NULL,
	relship varchar(2) NULL,
	ret varchar(6) NULL,
	retx varchar(1) NULL,
	sch varchar(1) NULL,
	schg varchar(1) NULL,
	schgw varchar(2) NULL,
	schla varchar(2) NULL,
	schlaw varchar(2) NULL,
	sem varchar(7) NULL,
	seml varchar(1) NULL,
	semx varchar(1) NULL,
	sex varchar(1) NULL,
	ss varchar(5) NULL,
	ssi varchar(5) NULL,
	ssix varchar(1) NULL,
	ssx varchar(1) NULL,
	ti varchar(8) NULL,
	til varchar(1) NULL,
	tin varchar(1) NULL,
	wag varchar(7) NULL,
	wagx varchar(1) NULL,
	wkh varchar(3) NULL,
	wkl varchar(1) NULL,
	wkwn varchar(2) NULL,
	wkwx varchar(1) NULL,
	wrk varchar(1) NULL,
	wrkj varchar(1) NULL,
	yoe varchar(4) NULL,
	cmid varchar(9) NOT NULL,
	pnum varchar(9) NOT NULL,
	CONSTRAINT pk_hu_mail_population PRIMARY KEY (cmid, pnum),
	CONSTRAINT fk_hu_mail_population_hu_mail_housing FOREIGN KEY (cmid) REFERENCES acme.hu_mail_housing(cmid)
);
